#!/bin/bash

set -e

rm -rf node_modules || true
./dev/npm install
./dev/npm dedupe
# Unneeded files
rm -f  node_modules/bluebird/js/browser/bluebird.min.js
rm -f  node_modules/cassandra-driver/node_modules/long/dist/Long.min.*
rm -rf node_modules/eslint/node_modules/js-yaml/dist
rm -rf node_modules/eslint/node_modules/js-yaml/node_modules/argparse/node_modules/sprintf-js/dist
rm -f  node_modules/eslint/node_modules/inquirer/node_modules/rx-lite/rx.lite.min.js
rm -f  node_modules/eslint/node_modules/inquirer/node_modules/rx-lite/rx.lite.map
# Re-patch node_modules/
for patchfile in ./dev/patches/???-*.patch; do
	echo -E "Applying $patchfile"
	patch -p1 < "$patchfile"
done
rm -f node_modules/request/request.js.orig
