#!/bin/bash

set -e

rm -rf node_modules
./dev/npm install
./dev/npm dedupe

# Unneeded files
rm -f  node_modules/cassandra-driver/node_modules/long/dist/Long.min.*
rm -rf node_modules/eslint/node_modules/js-yaml/dist
rm -rf node_modules/eslint/node_modules/js-yaml/node_modules/argparse/node_modules/sprintf-js/dist
rm -f  node_modules/eslint/node_modules/inquirer/node_modules/rx-lite/rx.lite.min.js
rm -f  node_modules/eslint/node_modules/inquirer/node_modules/rx-lite/rx.lite.map
rm -rf node_modules/googleapis/node_modules/google-auth-library/node_modules/gtoken/test
rm -f  node_modules/googleapis/node_modules/google-auth-library/node_modules/gtoken/node_modules/google-p12-pem/node_modules/node-forge/nodejs/ui/test.min.js
rm -f  node_modules/cassandra-driver/build.yaml
rm -rf node_modules/request/node_modules/qs/dist
# Web bundles
rm -f  node_modules/mocha/mocha.js
rm -rf node_modules/bluebird/js/browser
# jade is only needed for mocha's htmlcov
rm -rf node_modules/mocha/node_modules/jade
# Some coverage leftovers?
rm -rf node_modules/eslint/node_modules/doctrine/coverage
# Only needed for eslint's HTML formatter
rm -rf node_modules/eslint/node_modules/handlebars

# Re-patch node_modules/
for patchfile in ./dev/patches/???-*.patch; do
	echo -E "Applying $patchfile"
	patch -p1 < "$patchfile"
done
rm -f node_modules/request/request.js.orig
