#!/bin/zsh

FIFOHOLDER_PIDS=()
SUBPROCESS_PIDS=()

DIR="$(mktemp -d)"
for i in {0..7}; do
	mkfifo "$DIR/fifo-$i"
	# needed just to keep the fifo open
	tail -f /dev/null > "$DIR/fifo-$i" &
	FIFOHOLDER_PIDS+=($!)
	"$@" < "$DIR/fifo-$i" &
	SUBPROCESS_PIDS+=($!)
done

idx=0
while read -r line; do
	echo -E "$line" >> "$DIR/fifo-$idx"
	if [ $idx -eq 7 ]; then
		idx=0
	else
		idx=$(($idx + 1))
	fi
done

for pid in "${FIFOHOLDER_PIDS[@]}"; do
	kill -9 "$pid"
done

# Would kill subprocesses, but we're not sure those pids haven't
# been reused.
