#!/bin/sh

export BLUEBIRD_DEBUG=1
./node_modules/.bin/eslint .
iojs --harmony --harmony-rest-parameters --strong-mode ./node_modules/.bin/_mocha tests/*.js
echo 'Now running integration tests...'
cd tests
PATH="$(dirname "$PWD")/bin:$PATH" python2 -S -B ../../hg-test-runner/run-tests.py --shell=zsh
