#!/bin/bash

. ./dev/setup-test-env

terastash_src=$(dirname -- $(dirname -- $(realpath -- $0)))

integration_tests_log="$(mktemp)"
integration_ret_file="$(mktemp)"
# Run integration tests in a subshell so that unit tests and integration tests run in parallel
(
	cd src/tests
	PATH="$terastash_src/bin:$PATH" python2 -S -B ../../../hg-test-runner/run-tests.py -j8 --shell=bash
	echo -E -n "$?" >> "$integration_ret_file"
) > "$integration_tests_log" 2>&1 &
integration_pid=$!

./node_modules/eslint/bin/eslint.js .
eslint_ret="$?"

./dev/js ./node_modules/mocha/bin/_mocha src/tests/*.js
mocha_ret="$?"

echo 'Waiting for integration tests to finish...'
wait "$integration_pid"
cat "$integration_tests_log"

integration_ret="$(cat "$integration_ret_file")"

rm -f "$integration_tests_log"
rm -f "$integration_ret_file"

if [[ mocha_ret -eq 0 && eslint_ret -eq 0 && integration_ret -eq 0 ]]; then
	exit 0
else
	echo "One or more test programs returned non-0 exit code:"
	echo "mocha:       $mocha_ret"
	echo "eslint:      $eslint_ret"
	echo "integration: $integration_ret"
	exit 1
fi
